### ISSUE TITLE
Only three types light fan or switch can you add blinds or doors or locks

### ISSUE THREAD

**Issue by cvalord** [howanghk/homebridge-ewelink#34] opened 2019-06-18 03:12 UTC
Hi good evening , I want to know how
can I add more types of swtiches

when I go to home app on my phone
It only appear (light, fan, switch)

Can you add or how can I add example
blinds , curtains , garage door , locks 

thank you very much

**Comment by howanghk** [comment] 2019-06-25 13:47
Duplicate of #33

**Closed by howanghk** 2019-06-25 13:47 UTC
Labels: duplicate
