### ISSUE TITLE
Scene with multiple devices sometimes fail

### ISSUE THREAD

**Issue by magnificent3** [howanghk/homebridge-ewelink#52] opened 2019-10-19 10:18 UTC
I have set up a scene in the home app where it turns on 2 or more devices.
It just turns 1 on although in the home app it shows up as if all are on.
Can you help?

**Comment by howanghk** [comment] 2019-10-22 08:23
Duplicate of https://github.com/howanghk/homebridge-ewelink/issues/51

**Closed by howanghk** 2019-10-22 08:23 UTC
