### ISSUE TITLE
[Error: certificate has expired] ewelink accessories showed "No Response" in Homekit

### ISSUE THREAD

**Issue by LegendaryWiz** [howanghk/homebridge-ewelink#100] opened 2020-06-06 10:58 UTC
I encountered a problem when I started Homekit, all of my Homebridge devices showed "No Response", even my Broadlink and TV plugins. I’ve to tap the tile once, wait for a few sec, then the last reported status will show up. From there I’m able to use Homebridge as per normal. However for ewelink devices all went offline and can’t be controlled at all from Homekit. (I can still control from native app, though)

I figured it may have to do with the ewelink max plugin. Here's the log. The main error log showed is "certificate has expired", which I've no idea what it means... I’m hoping ewelink didn’t suddenly remove support for Homebridge, somehow. 
I've tried most troubleshooting, rebooting, reinstalling the plugin, removing ewelink from config.json and adding it back, etc. All failed to return a normal state. However, when I uninstalled the ewelink plugin, all other devices from other plugins returned normal. I even tried installing other Ewelink plugin variations or forks. All logs returned with something along the lines of “cert has expired” 

Anyone can tell me how I can go about resolving this? Or if this is a bug that suddenly surfaced? I'm more concerned about how I get ewelink back to working state since I use it in an automation sequence every day. Thank you very much 🙂

Below is the log shown when Homebridge started:
[2020-6-6 11:06:09] [eWeLink] A total of [1] accessories were loaded from the local cache
[2020-6-6 11:06:09] [eWeLink] Sending login request with user credentials: {"email":"**************@yahoo.com","password":"hidden_for_security","version":"6","ts":"1591412769","nonce":"159141276970900","appid":"oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq","imei":"2DB055BB-30E2-4BAB-BCD2-B817D0778B5B","os":"iOS","model":"iPhone10,6","romVersion":"11.1.2","appVersion":"3.5.3"}
[2020-6-6 11:06:09] [eWeLink] Login signature: XJRkBkPz+T1nvLdyJG+aBXatlUCOY8fCTI+iJueSXk4=
[2020-6-6 11:06:09] Homebridge is running on port 39221.
[2020-6-6 11:06:10] [eWeLink] An error was encountered while logging in. Error was [Error: certificate has expired]
[2020-6-6 11:06:10] [eWeLink] Requesting a list of devices from eWeLink HTTPS API at [https://eu-api.coolkit.cc:8080]
[2020-6-6 11:06:11] [eWeLink] An error was encountered while requesting a list of devices. Error was [Error: certificate has expired]
[2020-6-6 11:07:56] [eWeLink] Requesting power state for [Water Heater]
[2020-6-6 11:07:57] [eWeLink] An error was encountered while requesting a list of devices while interrogating power status. Verify your configuration options. Error was [Error: certificate has expired]

**Comment by howanghk** [comment] 2020-06-08 15:29
Duplicate of https://github.com/howanghk/homebridge-ewelink/issues/94

**Closed** 2020-06-08 15:29 UTC
