### ISSUE TITLE
Sonoff LED

### ISSUE THREAD

**Issue by profx5015** [howanghk/homebridge-ewelink#37] opened 2019-07-10 14:41 UTC
Hello!
Is there an ability to add dimming and color selection to sonoff LED?
Thanks in advance!

**Comment by howanghk** [comment] 2019-07-10 15:27
Hi @profx5015, as written in the README, this plugin only works for Sonoff basic relay (only 1 on/off switch). As I do not have other ewelink device except the basic switch one, it is very hard (if not impossible) for me to implement support for those devices.
It seems ByronTudhope is working on adding dimmer support to the ewelink plugin, you can find his fork here: https://github.com/ByronTudhope/homebridge-ewelink-max

Duplicate of #28

**Closed by howanghk** 2019-07-10 15:27 UTC
