### ISSUE TITLE
Websocket error 400 again

### ISSUE THREAD

**Issue by John88a** [howanghk/homebridge-ewelink#70] opened 2019-12-24 08:06 UTC
@howanghk
Hi all, since yesterday im getting the error 400 again...
I updated the ewe link max plugin, but still the same, this is the error:
[2019-12-24 13:15:03] [eWeLink] WebSocket messge received: {"error":400,"reason":"Bad Request","apikey":"fc37d794-8eff-420f-b91f-55ddef613649","sequence":"1577164503449","actionName":"userOnline"}

**Comment by howanghk** [comment] 2019-12-24 09:24
Duplicate of #67

**Closed by howanghk** 2019-12-24 09:24 UTC
