### ISSUE TITLE
2-Gang Wall Switch not working 

### ISSUE THREAD

**Issue by bartgabriels** [howanghk/homebridge-ewelink#87] opened 2020-05-11 14:46 UTC
Hi,

I installed today my first 2-Gang wall switch, and now HomeBridge keeps crashing. 
Installed version: homebridge-ewelink-max v0.1.21

Here are the logs:
[5/11/2020, 16:44:30] [eWeLink] SC SK Zussen CH 1 Configure Accessory
[5/11/2020, 16:44:30] [eWeLink] SC SK Zussen CH 2 Configure Accessory
[5/11/2020, 16:44:30] [eWeLink] SC SK Zussen CH 1 Configure Accessory
[5/11/2020, 16:44:31] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: dcbb77f8-cd56-4d8f-a6af-c897f3432f1d
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
[5/11/2020, 16:44:31] Got SIGTERM, shutting down Homebridge...

**Comment by howanghk** [comment] 2020-05-11 17:25
Duplicate of #73

**Closed by howanghk** 2020-05-11 17:25 UTC

**Comment by bartgabriels** [comment] 2020-05-11 17:34
Indeed, fixed after removing cache.
